repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-toml
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev:  5.0.4  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        additional_dependencies: [Flake8-pyproject]
-   repo: local
    hooks:
    -   id: export-req
        name: export requirements
        language: system
        pass_filenames: false
        entry: poetry export -f requirements.txt -o requirements.txt --without-hashes
        files: ^(pyproject.toml|poetry.lock)$
