services:
  model-api:
    build: .
    ports:
      - "8000:8000"
    links:
      - influx
  influx:
    build:
      context: ./docker/influxdb
    hostname: influx
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_DB=testDB
      - INFLUXDB_USER=admin
      - INFLUXDB_PASSWORD=pass123
volumes:
  influxdb-storage: